version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tradyzer-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tradyzer_db
      POSTGRES_USER: tradyzer_user
      POSTGRES_PASSWORD: tradyzer_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tradyzer_user -d tradyzer_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tradyzer-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: tradyzer-adminer
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha-dark

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: tradyzer-network